## Test python file

In [5]:
import numpy as np

In [8]:
# Loading data from file
file_data = np.genfromtxt('data_files/npdata.txt', delimiter=',')
file_data = file_data.astype('int32')
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean masking and Avanced indexing

In [10]:
file_data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [12]:
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [16]:
# Index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,5]]

array([2, 3, 6])

In [17]:
np.any(file_data > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [18]:
np.all(file_data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [19]:
((file_data > 50) & (file_data < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [20]:
(~((file_data > 50) & (file_data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [26]:
### Quick test
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a = b[2:4,0:2]
a

array([[11, 12],
       [16, 17]])

In [29]:
c = [b[0,1], b[1,2], b[2,3], b[3,4]]
c

[2, 8, 14, 20]

In [30]:
c2 = b[[0,1,2,3],[1,2,3,4]]
c2

array([ 2,  8, 14, 20])

In [31]:
d = b[[0,2],3:]
d

array([[ 4,  5],
       [14, 15]])